// IA page content — generated by the smc-ia-content workflow (grounded in real
// product facts + cited research), curated here. Edit freely; regenerate rarely.

/* eslint-disable */
export const IA_CONTENT = {
  "framework": {
    "how": [
      "Watch how the decision usually happens. A student finishes class 10 or 12. At home, a parent who lived through a bad decade wants a floor under the child. From outside, hearsay — a cousin placed at a software firm, a coaching hoarding on the school route. From these fragments the family builds a picture of work, maybe ten careers wide, and chooses from inside it. Made at fifteen or seventeen, on the least information the family will ever have — when it matters most.",
      "Under the noise, three confusions do most of the damage. Interest is mistaken for aptitude — liking a subject is read as being built for its profession. Familiarity is mistaken for options — the ten visible careers stand in for the thousands that exist. And marks are mistaken for direction — a good score in biology is treated as a verdict that medicine must follow. Each confusion feels like reasoning while it is happening. None of it is evidence.",
      "Measurement changes the conversation. Not because a test knows a child better than a parent does — it does not — but because it brings information nobody in the room has. A measured aptitude profile, a scored interest inventory, a personality assessment: these turn a shouting match into a document two people can read at the same table. The argument moves from who is loudest to what is true.",
      "Measurement does not make the decision. It narrows the field, shows its reasoning, and leaves the deciding where it belongs — with the person who has to live inside the choice. The four factors below are what we measure, and why."
    ],
    "model": {
      "intro": "One factor alone misleads. Strong aptitude without interest produces a competent, unhappy professional. Strong interest without market reality produces an educated, unemployed one. We measure four factors and trust only the paths where they agree.",
      "factors": [
        {
          "name": "Aptitude",
          "question": "Where will effort compound fastest?",
          "instrument": "A multi-part aptitude battery — verbal, numerical, abstract and spatial reasoning — scored live online. It finds the kind of thinking that costs you less than it costs others, which is where years of study go furthest."
        },
        {
          "name": "Interest",
          "question": "What holds your attention when no one is grading you?",
          "instrument": "The RIASEC interest inventory, built on Holland's six vocational types. It measures what you return to unprompted — the fuel a long course of study actually runs on."
        },
        {
          "name": "Personality",
          "question": "In what conditions do you do your best work?",
          "instrument": "A Big Five personality assessment — openness, conscientiousness, extraversion, agreeableness, emotional stability. It describes how you work: with people or alone, under structure or without it, steady or in bursts."
        },
        {
          "name": "Market reality",
          "question": "Will the work exist, and will it pay?",
          "instrument": "Labour-market analysis: hiring demand, seat availability, admission odds, cost of the degree and expected return in rupees. Not a psychometric — a check the other three factors must pass before a path is recommended."
        }
      ],
      "synthesis": "The four are read together, not in sequence. AI drafts the mapping — career paths scored against all four profiles, with the paths where the factors converge rising to the top. A single loud factor is never enough. Then a certified counsellor does the real work: reads the draft against everything the tests cannot see, edits it, and owns the recommendation. What reaches you is a ranked shortlist with the reasoning shown — why each path fits, what it demands, what the admission odds are, and what it returns."
    },
    "science": {
      "intro": "None of these instruments were invented here. They are the three most-studied traditions in a century of vocational psychology. We use them because the evidence holds — and we will tell you where it stops.",
      "pillars": [
        {
          "name": "RIASEC interests",
          "what": "Six vocational interest types — Realistic, Investigative, Artistic, Social, Enterprising, Conventional. Every person and every occupation is a blend of the six. Fit is the overlap between your blend and the work's.",
          "evidence": "Proposed by John Holland in 1959 and refined over four decades, it is the most replicated framework in vocational psychology and underpins O*NET, the US Department of Labor's occupational database. The honest limit: interest fit predicts satisfaction and persistence better than it predicts performance. It tells you what you will stay with, not what you will be best at."
        },
        {
          "name": "Big Five personality",
          "what": "Five broad traits — openness, conscientiousness, extraversion, agreeableness, emotional stability — that describe a person's characteristic way of working, and which working environments will wear them down.",
          "evidence": "The consensus model of academic personality psychology, built from fifty years of lexical and statistical research — Tupes and Christal in the 1960s, Costa and McCrae through the 1990s. Meta-analyses since Barrick and Mount (1991) find conscientiousness predicts job performance across nearly every occupation. The honest limit: the effects are moderate. Traits are tendencies, not destiny, and they shift somewhat with age."
        },
        {
          "name": "Aptitude testing",
          "what": "Timed measures of reasoning — verbal, numerical, abstract, spatial. They estimate where you learn fastest, which is where a long education costs you least.",
          "evidence": "The oldest lineage in psychometrics, running from early twentieth-century ability testing to multi-aptitude batteries like the DAT (1947) and GATB. Schmidt and Hunter's 1998 review of eighty-five years of data found general ability the single strongest predictor of training success. The honest limit: a score is a snapshot, sensitive to schooling and practice. It says where learning is cheaper — not what a life should be about."
        }
      ]
    }
  },
  "solutions": {
    "segments": [
      {
        "id": "students",
        "label": "Students",
        "headline": "You are not your rank",
        "body": "A rank sorts you against a million strangers; it has never once described you. We measure what does — aptitude, interest and temperament — then a certified counsellor maps it to a stream, and to the exams worth two years of your life. The choice is argued from who you are, not from where you placed.",
        "gets": [
          "Big Five, RIASEC and aptitude assessments, scored live online",
          "A readable report: matched streams, strengths, and the reasoning behind each",
          "A certified counsellor who interprets the data and answers your questions on video"
        ],
        "start": "Start with the free Career Clarity Index — four minutes — then take the Stream Selector at ₹1,990 when the question turns serious."
      },
      {
        "id": "parents",
        "label": "Parents",
        "headline": "Put the weight down",
        "body": "Right now the decision is a negotiation between your fear and your child's hopes, and you are carrying it alone. We put the evidence on the table — so the choice stops being yours to win and starts being theirs to own, guided by a counsellor who owns the recommendation, not you.",
        "gets": [
          "A seat in every counselling session, on video",
          "Shared access to your child's report and progress",
          "Admission odds and ROI for each recommended path, in rupees"
        ],
        "start": "Have your child take the free Career Clarity Index; it gives the first session something concrete to work with."
      },
      {
        "id": "graduates",
        "label": "Graduates",
        "headline": "A degree is not a direction",
        "body": "A degree tells the world what you studied. It does not tell you what to do next. The Job Domain Selector measures what you are built for and maps it to the domains that actually hire — trade-offs stated plainly, so the next move is decided, not defaulted into.",
        "gets": [
          "An aptitude, interest and personality profile matched to specific job domains",
          "A report with reasoning: why these domains, and why not others",
          "An AI career counsellor in your portal, grounded in your own results, plus video sessions with a certified counsellor"
        ],
        "start": "Start with the Job Domain Selector at ₹2,490 — it is built for exactly this decision."
      },
      {
        "id": "professionals",
        "label": "Working Professionals",
        "headline": "Right on paper",
        "body": "The plateau, the golden handcuffs, the quiet certainty that you are in the wrong life. Too late is a guess. A switch is only a decision with a price — what transfers, what it costs to move, what the market pays on the other side — and a senior counsellor works it until the numbers hold.",
        "gets": [
          "A full psychometric profile read against your work history",
          "Matched paths with earning reality and switching costs, in rupees",
          "One certified counsellor who stays with your case from assessment to decision"
        ],
        "start": "Start with Full Career Counselling, quoted to your situation — career changes are rarely off the shelf."
      },
      {
        "id": "schools",
        "label": "Schools",
        "headline": "Every student counselled, not just the toppers",
        "body": "Stream choice arrives in Class 9 and 10 whether a school is ready or not. We run standardised assessments across the cohort and put certified counsellors behind every report — a scale one school counsellor cannot reach alone.",
        "gets": [
          "Online assessments for a full cohort, scored live",
          "An individual report for every student, reviewed by a certified counsellor",
          "Parent access to sessions and reports, so guidance continues at home"
        ],
        "start": "Start with the Stream Selector for a pilot batch; institutional pricing is quoted on cohort size."
      },
      {
        "id": "colleges",
        "label": "Colleges",
        "headline": "From enrolment to employment, with evidence",
        "body": "Placement season exposes choices made three years earlier. Domain-level assessment early in the degree helps students aim at work that fits them, and gives your placement cell data instead of guesswork.",
        "gets": [
          "Job Domain Selector assessments across departments or batches",
          "Per-student reports mapping aptitude and interests to hiring domains",
          "Counsellor-led video sessions students book from their own portal"
        ],
        "start": "Start with the Job Domain Selector for one batch; institutional pricing is quoted on numbers."
      },
      {
        "id": "organizations",
        "label": "Organizations",
        "headline": "Right people, right roles",
        "body": "Poor fit costs more than salary. The same instruments we use for careers — Big Five, RIASEC, aptitude batteries — read against your roles, with a certified counsellor's interpretation rather than a dashboard's.",
        "gets": [
          "Psychometric profiles for employees, scored on real instruments",
          "Counsellor-interpreted reports on fit, strengths and development",
          "Structured sessions for internal mobility and growth conversations"
        ],
        "start": "Start with Full Career Counselling, quoted per engagement — team size and intent shape the design."
      }
    ]
  },
  "library": {
    "careers": [
      {
        "name": "Software Engineer",
        "cluster": "Engineering & Technology",
        "line": "Most days are reading code, fixing bugs and reviewing others' work; writing something new is the smaller part."
      },
      {
        "name": "Data Scientist",
        "cluster": "Data & Analytics",
        "line": "Cleaning data and explaining results to people who wanted a different answer; the model is the last ten percent."
      },
      {
        "name": "Mechanical Engineer",
        "cluster": "Engineering & Technology",
        "line": "CAD drawings, tolerance checks, vendor calls and shop-floor visits; the desk and the factory in equal measure."
      },
      {
        "name": "Doctor (MBBS)",
        "cluster": "Medicine & Health",
        "line": "Long shifts of patients, case notes and decisions that cannot wait; independence comes a decade after you start."
      },
      {
        "name": "Clinical Psychologist",
        "cluster": "Psychology & Counselling",
        "line": "Sitting with people in pain one hour at a time, with notes after every session; an RCI-recognised MPhil before you may practise."
      },
      {
        "name": "UX Designer",
        "cluster": "Design",
        "line": "Interviewing users, sketching flows and defending decisions in meetings; less drawing than outsiders imagine."
      },
      {
        "name": "Architect",
        "cluster": "Design & Built Environment",
        "line": "Drawings, site visits, municipal approvals and clients who change their minds; buildings answer slowly."
      },
      {
        "name": "Corporate Lawyer",
        "cluster": "Law",
        "line": "Reading contracts line by line and marking risk before deadlines; courtrooms are rare, precision is daily."
      },
      {
        "name": "Chartered Accountant",
        "cluster": "Finance & Accounting",
        "line": "Audit files, tax filings and client deadlines, learned through years of articleship; the detail is the job."
      },
      {
        "name": "Product Manager",
        "cluster": "Business & Management",
        "line": "Writing specs, prioritising ruthlessly and saying no politely; you own the outcome without owning the team."
      },
      {
        "name": "Journalist",
        "cluster": "Media & Communication",
        "line": "Calls, sources and same-day deadlines; half the work is verifying what someone told you."
      },
      {
        "name": "Civil Servant (IAS)",
        "cluster": "Government & Public Service",
        "line": "Files, field visits and decisions that touch whole districts; the exam is one year of a thirty-year job."
      }
    ],
    "degrees": [
      {
        "name": "B.Tech Computer Science",
        "leadsTo": "Software, data and product roles. The degree opens the door; what you build outside class decides the room."
      },
      {
        "name": "MBBS",
        "leadsTo": "Clinical practice, with NEET-PG deciding the specialty. General medicine, hospital jobs, or further study abroad."
      },
      {
        "name": "B.Des",
        "leadsTo": "UX, product, communication or industrial design. The portfolio outweighs the college name."
      },
      {
        "name": "BA LLB (five-year)",
        "leadsTo": "Litigation, law firms, judiciary exams or in-house counsel. Internships during college set the track."
      },
      {
        "name": "B.Sc–M.Sc (Sciences)",
        "leadsTo": "Research, teaching and lab roles. Most of the value arrives at the master's, not the bachelor's."
      },
      {
        "name": "B.Com",
        "leadsTo": "Accounting, banking and finance operations. Broad by default; sharp only with CA, CS or CMA alongside."
      },
      {
        "name": "BBA",
        "leadsTo": "Entry management and sales roles, and a runway to an MBA. The institute's brand carries much of the value."
      },
      {
        "name": "BA Psychology",
        "leadsTo": "Counselling, HR and UX research. A master's is required to practise; RCI licensure for clinical work."
      },
      {
        "name": "B.Arch",
        "leadsTo": "Architecture practice, urban design and interiors after Council of Architecture registration. Five years, then patient years."
      },
      {
        "name": "BA Economics",
        "leadsTo": "Analytics, policy, banking and a strong base for a master's abroad. Quantitative electives decide the ceiling."
      }
    ],
    "skills": [
      {
        "name": "Programming",
        "paysIn": "Software companies, fintech and startups; freelance work adds a second income."
      },
      {
        "name": "SQL and data analysis",
        "paysIn": "Banks, e-commerce, consulting — anywhere data sits in tables."
      },
      {
        "name": "Clear writing",
        "paysIn": "Content, UX, law, journalism and every job that runs on email."
      },
      {
        "name": "Financial modelling",
        "paysIn": "Investment banking, equity research and startups raising money."
      },
      {
        "name": "Interface design (Figma)",
        "paysIn": "Product companies, agencies and freelance UI work."
      },
      {
        "name": "Statistics",
        "paysIn": "Data science, research, actuarial work and A/B testing at product firms."
      },
      {
        "name": "Public speaking",
        "paysIn": "Sales, teaching, consulting and every leadership track."
      },
      {
        "name": "Machine learning",
        "paysIn": "AI teams at product companies and research labs; a premium over plain engineering."
      },
      {
        "name": "Digital marketing",
        "paysIn": "D2C brands, agencies and the creator economy."
      },
      {
        "name": "Negotiation",
        "paysIn": "Sales, law, procurement — and every salary conversation you will have."
      }
    ],
    "industries": [
      {
        "name": "IT & SaaS",
        "note": "Hiring recovered after the 2023–24 freeze; AI skills now sort resumes into two piles."
      },
      {
        "name": "Healthcare",
        "note": "Grows regardless of cycles. India remains short of doctors, nurses and allied health workers."
      },
      {
        "name": "Financial services & fintech",
        "note": "UPI made India a laboratory for payments. Regulation tightens; the sector compounds anyway."
      },
      {
        "name": "Renewable energy",
        "note": "Solar and green hydrogen targets create engineering and project work through the 2030s."
      },
      {
        "name": "E-commerce & quick commerce",
        "note": "Fast growth on thin margins. Operations and analytics roles outnumber the glamorous ones."
      },
      {
        "name": "Manufacturing & EV",
        "note": "PLI schemes and EV lines are pulling factories back; mechatronics beats plain mechanical."
      },
      {
        "name": "Media & creator economy",
        "note": "More creators than ever; most earn little. Skills transfer, audiences do not."
      },
      {
        "name": "Education & EdTech",
        "note": "The boom corrected hard. Teaching endures; edtech now rewards proven outcomes, not funding rounds."
      }
    ],
    "emerging": [
      {
        "name": "AI Engineer",
        "line": "High pay, high bar. Mathematics and engineering together, not prompt-writing."
      },
      {
        "name": "Cybersecurity Analyst",
        "line": "Every digitising company is a target; trained people remain scarce."
      },
      {
        "name": "ESG Analyst",
        "line": "Companies must now report emissions, and someone has to count them."
      },
      {
        "name": "Data Privacy Officer",
        "line": "The DPDP Act made data protection a compliance profession almost overnight."
      },
      {
        "name": "Space Systems Engineer",
        "line": "Private launch firms now hire beyond ISRO. A small sector, but real rockets."
      },
      {
        "name": "Genetic Counsellor",
        "line": "Genomic tests are getting cheap; explaining them to patients is a new profession."
      }
    ],
    "comparisons": [
      {
        "a": "Engineering",
        "b": "Design",
        "verdict": "Engineering rewards how things work; design rewards how people use them. Pick by the question you cannot stop asking."
      },
      {
        "a": "CA",
        "b": "MBA",
        "verdict": "CA is depth — exams, articleship, a protected profession, low cost. MBA is breadth — brand, network, options — and pays only as well as the institute you get into."
      },
      {
        "a": "JEE",
        "b": "Design entrances (UCEED/NID)",
        "verdict": "Same years of preparation, different muscles: JEE tests speed with maths and physics; UCEED and NID test observation and drawing. Attempt a mock of each — the honest answer comes fast."
      },
      {
        "a": "Computer Science",
        "b": "Psychology",
        "verdict": "CS pays sooner and scales; psychology needs a master's before it pays at all. UX research and behavioural data are the bridge if you want both."
      }
    ],
    "intro": "Careers look different from the inside. This library describes the daily work, not the brochure — twelve careers, ten degrees, ten skills, and the industries around them. Read what interests you. Then test it against who you are."
  },
  "trust": {
    "methodology": [
      "Every recommendation starts with measurement. A student sits three real instruments online — a Big Five personality inventory, a RIASEC interest inventory, and aptitude batteries for verbal, numerical and spatial reasoning — scored live, by the same logic every time. No hunch, no parent's preference, no coaching-class default enters the data. The method has held since 2010: assess, interpret, map, decide, support.",
      "Scores decide nothing on their own. AI drafts the report — profile against career paths, admission odds and labour-market projections, with its reasoning shown. Then a certified counsellor reads it against the raw scores, corrects it, and signs the recommendation. Where the draft and the data disagree, the counsellor's judgement wins, and the report says why.",
      "We check the work. Every report shows which scores drove which matches, so a student, parent or another counsellor can trace each claim to the instruments. Labour-market figures come from named public sources, cited on this site and replaced when newer data lands. Fifty-five counsellors, 71,537 assessments and 101,780 hours of counselling feed back into the method."
    ],
    "research": [
      {
        "source": "Holland's RIASEC model of vocational interests",
        "grounds": "The interest inventory. Six interest types — Realistic, Investigative, Artistic, Social, Enterprising, Conventional — scored into a profile that maps to occupation families. The six-question demo on the product page runs the same scoring logic at miniature scale."
      },
      {
        "source": "Big Five personality research",
        "grounds": "The personality instrument. Five broad traits with decades of evidence behind them, used to judge temperament fit — how a student tends to operate, as distinct from what they can do or what draws them."
      },
      {
        "source": "US Bureau of Labor Statistics, Employment Projections 2024",
        "grounds": "US occupation growth figures in the careers-in-motion demo: wind turbine technicians, solar PV installers, nurse practitioners, data scientists, information security analysts, 2023–2033."
      },
      {
        "source": "World Economic Forum, Future of Jobs Report 2025",
        "grounds": "Global role projections in the same demo: big data specialists, fintech engineers, AI and machine learning specialists, and the 78 million net new jobs expected by 2030."
      },
      {
        "source": "National Testing Agency, NEET 2024 figures",
        "grounds": "The 23 lakh figure — students who sat a single entrance exam in 2024. It grounds our case that most career decisions in India are made under pressure, before anyone measures the student."
      },
      {
        "source": "India Skills Report 2024",
        "grounds": "The 51 per cent figure — barely half of Indian graduates assessed as employable, years and fees after the stream decision. The cost of choosing blind."
      },
      {
        "source": "Harris Poll for CNBC, 2021",
        "grounds": "The 47 per cent of adults who wish they had chosen a different career path. The human cost, visible only later."
      },
      {
        "source": "NASSCOM, 2023",
        "grounds": "India's projected demand for AI and data talent — over a million roles by 2026 — in the careers-in-motion demo."
      }
    ],
    "privacy": [
      "Your assessment data exists to guide you. It scores your instruments, drafts your report and informs your counsellor. It is not used for anything else.",
      "We do not sell your data. Not to coaching institutes, not to colleges, not to advertisers. Your scores are never the product.",
      "Sessions are confidential. What a student says stays between the student, their counsellor and — where the family holds shared access — their parents.",
      "Parents see the report and progress through shared access, and the student knows it. No hidden mirrors.",
      "Ask, and we delete. Assessment records, chat history and reports are removed on request."
    ],
    "ethics": {
      "stance": "AI makes our work faster and more consistent. It does not make it autonomous. The machine drafts; a certified counsellor interprets, edits and owns every recommendation. A decision this large deserves a person who can be questioned and held to their reasoning.",
      "lines": [
        "AI never issues the final recommendation. Every report is read, corrected and signed by a certified counsellor before a family sees it.",
        "The AI counsellor in the portal is grounded in the student's own results. It does not invent careers, improvise statistics, or diagnose.",
        "No dark patterns. Prices are stated in rupees up front, the first assessment is free, and nothing is charged or renewed without a clear yes.",
        "Measurement, not surveillance. We score what a student chooses to sit for. We do not track behaviour, scrape profiles, or assess anyone who has not asked.",
        "We do not flatter. If the data points away from the family's preferred path — engineering, medicine, anything — the report says so, plainly."
      ]
    }
  },
  "pricing": {
    "positioning": "The tests are the easy part; what you pay for is a certified counsellor's judgment, and the first look at yourself is free.",
    "tiers": [
      {
        "name": "Career Clarity Index",
        "price": "Free",
        "who": "For anyone who wants to know how clear they actually are before spending a rupee.",
        "includes": [
          "A short structured self-check, done online",
          "A clarity score showing where you stand today",
          "A plain reading of what the score means",
          "A pointer to the next step, if you need one"
        ],
        "time": "About 4 minutes."
      },
      {
        "name": "Stream Selector",
        "price": "₹1,990",
        "who": "For students in classes 8–10 choosing between Science, Commerce and Arts.",
        "includes": [
          "RIASEC interest inventory, Big Five personality and aptitude battery, scored live online",
          "A stream recommendation a certified counsellor interprets, edits and signs",
          "A readable report: matched streams, your strengths, and the reasoning behind the call",
          "Portal access with an AI career counsellor grounded in your own results",
          "Shared access for parents to the report and progress"
        ],
        "time": "Tests in one sitting. The report follows once a counsellor has reviewed it."
      },
      {
        "name": "Job Domain Selector",
        "price": "₹2,490",
        "who": "For students in classes 11–12 and early graduates deciding which field to work toward.",
        "includes": [
          "The full battery: Big Five, RIASEC and aptitude, scored live online",
          "A counsellor-owned report mapping matched job domains and the degree paths into them",
          "Admission odds and return on investment for the paths that fit you",
          "AI career counsellor in the portal, grounded in your results, plus video session booking",
          "Shared access for parents to the report and progress"
        ],
        "time": "Tests in one sitting. The report follows once a counsellor has reviewed it."
      },
      {
        "name": "Full Career Counselling",
        "price": "Quoted",
        "who": "For families who want a counsellor from the first test to the final decision, and after it.",
        "includes": [
          "The complete method: Assess, Interpret, Map, Decide, Support",
          "The full assessment battery and a counsellor-owned career report",
          "Video sessions with a certified counsellor, with parents welcome in the room",
          "Ongoing support as the decision plays out — exams, admissions, second thoughts"
        ],
        "time": "Scoped and quoted after a first conversation. Support runs as long as the decision needs."
      }
    ],
    "faq": [
      {
        "q": "Do you offer refunds?",
        "a": "If you pay and change your mind before starting the assessments, write to us and we refund in full. Once a counsellor has reviewed your results and the report exists, the work is done and the fee stands."
      },
      {
        "q": "What if I am not sure which package I need?",
        "a": "Take the free Career Clarity Index first — four minutes. Choosing a stream after class 10 points to the Stream Selector. Choosing a field of study or work after that points to the Job Domain Selector. If the whole decision feels heavy, ask us to quote Full Career Counselling."
      },
      {
        "q": "How do counselling sessions work?",
        "a": "You book a video session from your portal. The counsellor arrives prepared — your assessment results and report are in front of them, not a blank file. Parents can join the session and keep shared access to the report and progress afterward. Every counsellor is certified, and the recommendation is theirs, not the software's."
      }
    ]
  },
  "book": {
    "steps": [
      {
        "title": "Pick a time",
        "body": "Choose a slot that works for your family. Sessions run on video, so you can join from home. Most parents pick an evening or weekend."
      },
      {
        "title": "Tell us a little",
        "body": "Your child's class, stream if chosen, and what is on your mind — a stream decision, an exam plan, or general direction. Two minutes, no forms beyond that."
      },
      {
        "title": "Meet your counsellor",
        "body": "A certified counsellor joins the call, listens first, and explains how the process works — assessments, the report, and what happens after. Parents are welcome on the call."
      }
    ],
    "reassurance": "The first conversation is just that — a conversation; you decide afterwards whether to go further."
  },
  "product": {
    "assessments": "The instruments are real psychometrics, not quizzes: Big Five personality, the RIASEC interest inventory, and aptitude batteries, scored live online — over 71,537 tests since 2010. Start free with the Career Clarity Index in about four minutes, then step up to Career Navigator for all three, scored, at ₹2,990.",
    "coach": "Compass speaks only from your own results — your interests, personality and aptitude — in chat or voice, whenever you need to think something through. It keeps the record live between sessions and hands the recommendation back to your certified counsellor.",
    "dashboards": [
      {
        "id": "dashboard",
        "name": "Client dashboard",
        "forWho": "Every client — a student, a graduate, a professional, a parent",
        "body": "A running record of one decision — and it keeps getting sharper. Take assessments scored live, talk to Compass grounded in your own results, book video sessions with a counsellor, and read the report when it is ready. Family members get shared access to the same record and progress, nothing new to learn.",
        "highlights": [
          "Assessments scored live online",
          "Chat or voice AI coach grounded in your own results",
          "Book video sessions and read your career report",
          "Shared access for family — the same evidence, one home"
        ]
      },
      {
        "id": "counselor",
        "name": "Counsellor console",
        "forWho": "The 55+ certified counsellors who own every recommendation",
        "body": "The working desk: caseload and calendar in one view, live video sessions with a running transcript, and review of every AI-drafted report before it reaches a family.",
        "highlights": [
          "Caseload and calendar together",
          "Live sessions with transcript",
          "Review and edit every report before it ships"
        ]
      }
    ],
    "overview": "SetMyCareer is a career decision-intelligence system. Validated assessments, certified counsellors and Compass are the inputs; the dashboard is the product — a record of one decision that only gets sharper the longer you use it.",
    "reports": "The report is written to be read: matched career paths, your strengths, the reasoning behind each match, and admission odds and ROI in rupees. Compass drafts it; a certified counsellor interprets, edits and owns every recommendation — and it re-generates as new evidence arrives.",
    "tour": [
      {
        "stop": "Sign up",
        "body": "Create an account and take the free Career Clarity Index — a first reading in about four minutes."
      },
      {
        "stop": "Assess",
        "body": "Sit the real instruments — Big Five personality, RIASEC interests, aptitude batteries — scored live online."
      },
      {
        "stop": "AI coach",
        "body": "Chat or talk with an AI career counsellor that knows your results, not someone else's averages."
      },
      {
        "stop": "Counsellor session",
        "body": "Book a video session where a certified counsellor interprets your scores — parents can join."
      },
      {
        "stop": "Report",
        "body": "Receive a readable career report: matched paths, strengths, reasoning, admission odds and ROI — drafted by AI, owned by your counsellor."
      }
    ]
  }
} as const
