// Site copy + editorial articles. Generated by the Career-Intelligence content
// agent (real, grounded writing) and curated here. Dates are editorial.

import { MORE_ARTICLES } from "./more-articles"

export interface MethodStep { no: string; title: string; body: string }
export interface ProductItem { title: string; body: string }

export const COPY = {
  heroKicker: "EST. 2010 · CAREER INTELLIGENCE",
  heroHeadline: "Measured,\nthen yours.",
  heroSub: "The largest decision of a life is made on its thinnest evidence — a rank, a rumour, the loudest voice at home. We measure who you actually are; the deciding stays yours.",
  ctaPrimary: "See where you stand",
  ctaSecondary: "The method",

  problemKicker: "THE PROBLEM",
  problemHeadline: "Most Careers Are Chosen Blind",
  problemBody:
    "Streams, exams and degrees are chosen under pressure — on hearsay, on rank, on the loudest voice at home. Everyone in the room measures the score; no one measures the person choosing.",

  methodKicker: "THE METHOD",
  methodHeadline: "Five Steps, One Decision",
  method: [
    { no: "01", title: "Assess", body: "Measure aptitude, interest and personality through validated psychometric instruments, not opinion." },
    { no: "02", title: "Interpret", body: "Read the results as a pattern. A trained counsellor turns scores into a clear picture of how you think and work." },
    { no: "03", title: "Map", body: "Translate that picture into specific streams, courses and fields that genuinely match who you are." },
    { no: "04", title: "Decide", body: "Weigh each option against real-world considerations: admission odds, return on investment and long-term fit." },
    { no: "05", title: "Support", body: "Stay with you through admissions, transitions and the questions that arrive after the decision is made." },
  ] as MethodStep[],

  productKicker: "WHAT YOU GET",
  productHeadline: "Counsel, Now Instrumented",
  productBody:
    "The judgement stays human. We have given it instruments — so the measuring is faster, the picture clearer, and the counsel is there the moment you need it.",
  product: [
    { title: "AI Career Counsellor", body: "A counsellor you can reach by chat or voice, any hour, grounded in your own results and our fifteen years of practice." },
    { title: "Live Psychometric Assessments", body: "Aptitude, interest and personality measured through validated tests, taken online and scored in real time." },
    { title: "AI Career Report", body: "A clear, readable report that turns your scores into matched paths, strengths and the reasoning behind each." },
    { title: "Career Intelligence", body: "Admission odds, return on investment and scholarship routes, set against your profile so each choice is informed." },
  ] as ProductItem[],

  expertsKicker: "THE NETWORK",
  expertsHeadline: "People Behind the Method",
  expertsBody:
    "Our counsellors are trained to read assessments with care and to talk with students and professionals without an agenda. The technology widens their reach. The judgement remains human, and it remains theirs.",

  proofHeadline: "Fifteen years of measuring first. Founded by Dr. Nandkishore Rathi, PhD, IIT Bombay.",

  startKicker: "GETTING STARTED",
  startHeadline: "A Few Minutes Is Enough",
  startBody:
    "Free, no form, no commitment — the clarity comes first. Whether to go further is yours to decide.",

  insightsKicker: "FIELD NOTES",
  insightsHeadline: "Reading on Careers and Choice",

  footerLine: "SETMYCAREER — we measure first.",
}

export interface Article {
  slug: string
  title: string
  dek: string
  category: string
  readMin: number
  author: string
  date: string // ISO
  pullQuote: string
  body: string
}

const CORE_ARTICLES: Article[] = [
  {
    slug: "what-to-automate-and-what-to-keep-human",
    title: "what to automate, and what to keep human",
    dek: "AI can do more of career guidance than most people expect — and far less of it than the marketing suggests. The line between the two is the whole question.",
    category: "Perspective",
    readMin: 4,
    author: "Dr. Nandkishore Rathi",
    date: "2026-06-18",
    pullQuote: "A test can tell you what you are good at. It cannot tell you what you are willing to suffer for.",
    body: `For fifteen years we have done one thing: help a person see themselves clearly enough to choose well. The tools have changed. The work has not. So when people ask whether artificial intelligence will replace career counselling, the honest answer is that it will replace parts of it, improve other parts, and leave the most important part untouched.

It helps to separate the work into two kinds. There is the work of measurement and pattern — gathering data, scoring it, comparing it against what is known. And there is the work of judgement and meaning — sitting with a person as they decide what kind of life they want, and what they are prepared to give up for it. AI is already good at the first. It is structurally unsuited to the second.

## What should be automated

Scoring and consistency. A well-designed psychometric instrument — aptitude, interest along RIASEC lines, personality along the Big Five — is more accurate when scored by machine than by hand. Software does not tire on the four-hundredth report, does not round generously for a likeable student, does not forget a sub-scale. Automation removes the small human errors that creep into repetitive measurement, and that is a genuine gain.

Breadth of information. No counsellor can hold every entrance route, every cut-off, every emerging role in their head. The sheer volume of pathways has outgrown memory. AI is well suited to retrieving, organising and keeping this current. Used this way, it widens the set of options a student is even aware of — which is often where the real failure of guidance begins.

First drafts and admin. Summarising a report, preparing a comparison of three colleges, drafting a statement of purpose for the student to then rewrite in their own voice, scheduling, reminders — removing this frees the counsellor to spend the hour on the person rather than the paperwork.

## What must stay human

Interpretation in context. A score is a sentence, not a verdict. The same aptitude profile means something different for a student who is the first in the family to finish school than for one with three engineers at the dinner table. Context, constraint and family expectation are not noise to be corrected for. They are the actual problem, and reading them requires a person.

The conversation about meaning. A test can tell you what you are good at. It cannot tell you what you are willing to suffer for. Career choices are rarely limited by ability; they are limited by fear, by money, by the quiet pressure to not disappoint. Surfacing that, gently, and helping someone separate their own voice from the voices around them — this is counselling, and it cannot be automated, because it depends on trust between two people.

Accountability. When a young person commits years to a path, someone must own the recommendation and stand behind it. A model cannot be accountable. It cannot notice that a student went quiet when a particular option came up, then follow that silence to what it conceals.

## The honest shape of it

The right design is not human versus machine. It is the machine doing the measuring, retrieving and drafting so well that the human is free to do the part only a human can: judgement, meaning and care. A counsellor armed with good instruments and good information is better than one without. A student handed only a generated report, with no one to interpret it, has been given data and called it guidance.

That is the line we hold. Automate the measurement. Keep the meaning human. The science earns the trust; the conversation is where the decision is actually made.`,
  },
  {
    slug: "what-career-counselling-actually-changes",
    title: "what career counselling actually changes",
    dek: "The internet has already given you the information. What it cannot give you is the decision.",
    category: "Perspective",
    readMin: 4,
    author: "Dr. Nandkishore Rathi",
    date: "2026-06-04",
    pullQuote: "Information is symmetrical. A decision is yours alone, and it is the part no search engine can hand you.",
    body: `Most people who come to career counselling are not short of information. They arrive having already read the course lists, the eligibility rules, the salary ranges, the cut-offs. A student deciding after the 10th can recite the streams. A professional thinking about a switch knows, roughly, what each path pays.

So if the information is already there, what is left to change? The answer is the thing the information never produces on its own: a decision.

## Information is abundant. Decisions are scarce.

Information is symmetrical. Everyone reading the same article gets the same facts. That is its strength and its limit. A brochure tells you what a course contains; it does not tell you whether it is a good fit for you. A salary figure describes a market; it does not describe your tolerance for the work that earns it. The web is excellent at answering "what exists." It is silent on "what should I do, given who I am."

A decision is asymmetrical. It depends on facts that are specific to one person — aptitude, interests, temperament, constraints, what they are willing to trade away. Two students with identical marks should often make different choices. Information cannot tell them apart. A decision must.

## What actually gets in the way

When a capable person stays stuck despite knowing the options, the obstacle is rarely missing information. It is usually one of a few familiar things.

Too many options, weighted equally. Fifteen plausible paths feel worse than three, because the mind cannot compare fifteen things at once. Without a way to rank them against what matters, every option looks defensible and none feels chosen.

Other people's voices standing in for your own. A stream picked because a cousin did well in it. A safe degree chosen to settle a parent's anxiety. Good counselling separates these out, so the person can see which preferences are theirs.

Confusing interest with aptitude, and both with the job. Liking a subject, being good at it, and enjoying the daily work it leads to are three different things. Many regretted choices come from collapsing them into one.

## What counselling adds

It measures what the person cannot see in themselves. Well-built psychometrics give an outside reading of strengths and inclinations that self-assessment tends to distort. People routinely over-rate what they enjoy and under-rate what they are quietly good at.

It narrows honestly. The point is not to hand back a longer list. It is to reduce a wide field to a small set of options that genuinely fit, and to be clear about why the others were set aside.

It surfaces trade-offs instead of hiding them. Every real path costs something — years, money, geography, the roads not taken. A decision made with the trade-offs in view is one a person can stand behind later, even when it gets hard.

## The real outcome

The output of good counselling is not a report. It is a person who can explain their own decision — what they chose, what they declined, and why. That explanation is what holds up months later, when the novelty has worn off and the work is just work.`,
  },
  {
    slug: "beyond-the-jee-neet-binary",
    title: "beyond the jee/neet binary",
    dek: "After class 12, the real choice is not engineering or medicine. It is a far wider map of degrees, domains and routes that most students are never shown.",
    category: "Perspective",
    readMin: 4,
    author: "SetMyCareer Research",
    date: "2026-05-20",
    pullQuote: "The binary is not a fact about the world. It is a fact about what the people around a student happened to know.",
    body: `For a large share of Indian students, the months after class 12 collapse into two letters: JEE or NEET. Engineering or medicine. The coaching is built for it, the dinner-table conversations assume it, and the question "what next?" quietly becomes "which of the two?" The trouble is not that engineering and medicine are poor choices. For some students they are exactly right. The trouble is that a binary is being treated as a map, when it is closer to two roads on a continent.

## Why the binary persists

The binary survives for understandable reasons. Both paths are legible: parents recognise the degree, the exam, the rough salary. Both have visible role models nearby. And both have an enormous coaching industry whose business depends on the funnel staying narrow. None of this makes them the best fit for any particular person. It makes them the most repeated.

## The map is wider than two roads

Step back and the actual terrain is broad. After class 12 a student can enter, among many others: the pure and applied sciences, where research and analytics careers begin; economics, increasingly quantitative and a strong feeder into finance, policy and data; commerce and finance proper, including the CA, CS and CMA professional routes; design across product, communication and fashion, entered through NID, NIFT and UCEED rather than JEE; architecture and planning; law, now a five-year integrated degree taken straight after school via CLAT; psychology and the wider social sciences; computer applications and data fields that do not require an engineering seat; hospitality and culinary arts; agriculture and allied health sciences such as physiotherapy, nutrition and nursing; and the liberal arts, which remain a serious foundation for writing, research, civil services and management.

This is not an exotic list. Every item on it is an established profession with employers, salaries and progression.

## Beyond degrees: domains and routes

A second mistake is to think only in degrees. Domains are the worlds a person eventually works inside: healthcare, climate and energy, public policy, media, manufacturing, financial services, education. The same degree can open several domains; the same domain can be entered through several degrees. Routes are the shapes a path can take: a single-honours degree, an interdisciplinary degree, a professional qualification taken alongside graduation, a diploma followed by lateral entry, or undergraduate study abroad. Most students are shown one route when in practice the route is a choice in its own right.

## How to read the wider map

The point is better matching, not more options. First, work from the person, not the exam. Established psychometrics give a usable starting frame: broad personality traits, interest patterns of the kind RIASEC describes, and genuine aptitudes measured rather than assumed. A student strong in spatial reasoning and visual thinking, indifferent to memorising biology, is being poorly served by being pushed at NEET. That is information, not failure.

Second, read the labour market honestly. The aim is not to chase whatever sounds hot, but to choose work that fits the person and is likely to exist and pay reasonably over a working life. Third, keep options open where the cost is low. Early years that build durable capability leave more doors open than narrow specialisation chosen at seventeen under pressure.

A good decision after class 12 is not the one that sounds most impressive at a family gathering. It is the one a student can still stand behind ten years on, having seen the whole map before deciding which road to take.`,
  },
  {
    slug: "science-behind-a-career-assessment",
    title: "the science behind a career assessment",
    dek: "What psychometrics can measure with confidence, what it cannot, and how to read your results without overreading them.",
    category: "Method",
    readMin: 4,
    author: "SetMyCareer Research",
    date: "2026-05-06",
    pullQuote: "An assessment narrows the field of plausible choices. It does not choose for you.",
    body: `A good career assessment is not a verdict. It is a measurement — and like any measurement, it is useful only when you understand what it measures, how precisely, and where its limits lie. The instruments behind a serious assessment have been studied for decades. They are neither magic nor astrology. Read correctly, they sharpen a decision. Read carelessly, they manufacture false certainty.

Three families of measurement do most of the work: personality, interests, and aptitude. Each answers a different question.

## Personality: how you tend to operate

The most established model in psychology is the Big Five — five broad traits along which people vary: openness, conscientiousness, extraversion, agreeableness, and emotional stability. These are not types or boxes. They are continuous dimensions, and almost everyone sits somewhere in the middle of most of them.

Of the five, conscientiousness has the most consistent link to performance across a wide range of jobs, because diligence and follow-through travel everywhere. The rest matter more situationally. What personality cannot tell you is whether you will be good at a specific subject. A reserved person can be an excellent doctor. Traits describe probabilities, not destinies.

## Interests: where your attention goes willingly

The RIASEC model sorts interests into six themes — Realistic, Investigative, Artistic, Social, Enterprising, and Conventional. It maps what kinds of activities you are drawn to, not what you can do.

Interest predicts persistence. If the daily texture of a job bores you, talent rarely survives the years it takes to compound. But you cannot express interest in work you have never seen. That is why an assessment should widen your options, not just confirm the ones already in your head.

## Aptitude: what you can do, with effort

Aptitude tests measure specific reasoning abilities — verbal, numerical, spatial, abstract, mechanical. Of the three families, aptitude has the strongest relationship with how quickly someone learns demanding work. But aptitude is a snapshot of present ability, not a ceiling. A modest spatial score does not bar you from engineering; it tells you where you will have to work harder.

## What the science can and cannot do

Used together, these instruments triangulate. Where strong aptitude, real interest, and a fitting temperament overlap, you find directions worth taking seriously. Where they conflict, you find exactly the tensions worth talking through before you commit years and fees to a path.

It also has firm limits. No test measures motivation over a decade, family circumstances, the state of the job market, or the person you are still becoming. The numbers are the easy part. The work is interpretation. The right way to read your results is as evidence — not instruction. Look for convergence across the three families. Treat surprises as questions, not commands.`,
  },
  {
    slug: "choosing-a-stream-after-class-10",
    title: "choosing a stream after class 10, calmly",
    dek: "A decision framework that holds steady when the people around you are sure they know best.",
    category: "Method",
    readMin: 4,
    author: "SetMyCareer Research",
    date: "2026-04-22",
    pullQuote: "A stream is not a verdict on your worth. It is a starting position, and starting positions can be revised.",
    body: `The choice after class 10 feels larger than it is. Most students experience it as a single irreversible verdict. In practice it is a starting position, not a sentence. The aim is to make that position a considered one, so the decision can hold its shape when relatives, classmates, and well-meaning parents apply pressure in different directions.

## Separate the decision from the noise

The hardest part is rarely the subject matter. It is the volume around it. Before weighing options, name the voices out loud. Write down who is pushing for what, and what each person actually wants for you underneath the advice. Usually it reduces to two honest wishes: that you will be financially secure, and that you will not regret the choice. The specific stream they attach to those wishes is just their best guess, formed from their own era.

## Three inputs, in order

First, aptitude — your pattern of natural strengths, the way of thinking that feels less effortful for you than for others. It tells you where steady effort will compound fastest, and it is the input families most often skip.

Second, interest — what holds your attention when no one is grading you. Interest sustains the years of study a field demands. But a liking for hospital dramas is not an interest in physiology. Test interest against the actual daily work of a field, not its image.

Third, and last, opportunity — the labour market, family finances, available colleges. This matters, but it belongs third. When opportunity leads, students chase whichever field is loudly in demand today and arrive five years later to find the queue has moved.

## Clear away two myths

The first is that science is the "safe" superset that keeps all doors open. It does keep engineering and medical routes available, but carrying subjects you have no aptitude for has a cost in marks, confidence and time. The second is that commerce and arts are fallback streams. Commerce leads to chartered accountancy, economics, finance, law and management. The humanities lead to law, civil services, design, psychology and research. A stream chosen well beats a "prestigious" stream endured badly.

## A note on reversibility

Almost nothing here is permanent. Streams can be bridged, exams re-attempted, degrees switched. The students who struggle most are rarely those who picked the "wrong" stream. They are those who picked under pressure, stopped thinking, and never revisited the choice. Decide carefully, then hold the decision lightly.`,
  },
  {
    slug: "restarting-a-career-after-a-break",
    title: "restarting a career after a break",
    dek: "Re-entry is a sequencing problem, not a confession. Here is how to order the steps so the gap stops doing the talking.",
    category: "Method",
    readMin: 5,
    author: "SetMyCareer Research",
    date: "2026-04-08",
    pullQuote: "A break is a line on a timeline, not a verdict on a person.",
    body: `Most people return to work carrying two things: a gap and an apology for it. The gap is unavoidable. The apology is optional, and it is usually the part that does the damage. When you lead with regret, you invite the room to treat the break as the headline. When you lead with what you can do now, the break becomes a footnote.

Breaks happen for ordinary reasons: caregiving, health, relocation, a layoff, study, burnout. None of these are character flaws. What employers actually screen for is not continuity but current capability and reliability going forward. Your job is to make those two things easy to see.

## First, separate the story from the skills

Before you touch a CV, do a plain audit. List what you can still do well, what has gone rusty, and what has genuinely changed in the field while you were away. Keep these in three columns and resist the urge to inflate any of them. Be specific about decay: a doctor returning after five years and a developer returning after five years face different gaps, because medicine and code age at different speeds.

## Sequence the repair before the search

The common mistake is to start applying immediately, get a run of silence, and conclude that the break is disqualifying. More often the sequence was simply wrong.

Start with a small, current proof of work. One short course, one certification, one freelance task, one volunteer project that touches the actual skill. A single recent, datable line quietly resets how the whole timeline reads.

Next, rebuild a few live connections before you need them. Most re-entry happens through people who already know your work, not through cold portals. Reach out to former colleagues with a clear, low-pressure note. You are not asking for a job; you are asking for current information and a warm introduction.

Only then go wide with applications, and target deliberately. Smaller organisations, returnship programmes, and contract roles are more open to non-linear paths than prestige employers with hundreds of applicants per opening.

## Frame the gap in one clean line

Prepare a single, calm sentence and stop there. "I took two years out for family care, used the last few months to update my skills, and I am now focused on returning to data analysis." No defensiveness, no over-sharing, no apology. The tone you set is the tone the interviewer adopts.

## Re-enter at the right altitude

Decide in advance whether you are returning at your old level, a step down to rebuild momentum, or sideways into an adjacent role. There is no shame in a deliberate step down that buys re-entry; there is real cost in holding out for an exact-match title the market is not offering. Pick the altitude on purpose, and you negotiate from a plan rather than from fear.`,
  },
]

export const ARTICLES: Article[] = [...CORE_ARTICLES, ...MORE_ARTICLES].sort((a, b) => b.date.localeCompare(a.date))

export const articleBySlug = (slug: string) => ARTICLES.find((a) => a.slug === slug)
