// AUTO-GENERATED from Complete_Inventory_Items_32_JobChr_WorkEnv.xlsx — the real
// interest-cluster, work-environment and job-characteristic item banks.

export const INTEREST_CLUSTERS: { key: string; label: string; items: string[] }[] = [
  { key: 'sales_business_development', label: 'Sales & Business Development', items: ['I enjoy convincing others to try something new or see my point of view.', 'I feel excited when I can talk about a product, service, or idea to people.', 'I like building relationships and meeting new people for opportunities.'] },
  { key: 'digital_search_based_marketing', label: 'Digital & Search-based Marketing', items: ['I enjoy exploring how social media or online ads influence what people buy.', 'I like the idea of making posts, videos, or content that can reach many people online.', 'I am curious about how websites appear on the top of Google or other search results.'] },
  { key: 'finance_accounting_banking', label: 'Finance, Accounting & Banking', items: ['I enjoy working with numbers and finding patterns in money or data.', 'I like keeping track of how money is spent or saved in real or pretend situations.', 'I am interested in knowing how banks, savings, and investments work.'] },
  { key: 'entrepreneurship_start_ups', label: 'Entrepreneurship & Start-ups', items: ['I like thinking of new ideas and how they could become small businesses.', 'I enjoy taking initiative to start projects with friends or classmates.', 'I am comfortable with some risk if it helps me build something new.'] },
  { key: 'general_management_strategy', label: 'General Management & Strategy', items: ['I enjoy planning group projects and deciding who should do which task.', 'I like setting goals for my team and checking if we are reaching them.', 'I am curious about how big companies make decisions for the future.'] },
  { key: 'human_resource_management', label: 'Human Resource Management', items: ['I like helping people solve problems at school or in a group.', 'I enjoy planning activities where everyone feels included and supported.', 'I am curious about how people are selected for jobs or teams.'] },
  { key: 'law_legal_services', label: 'Law & Legal Services', items: ['I enjoy debating and defending my point of view with strong reasons.', 'I like reading or hearing about real-life cases, justice, and fairness.', 'I feel interested in knowing people’s rights and responsibilities in society.'] },
  { key: 'public_policy_governance', label: 'Public Policy & Governance', items: ['I am interested in how governments make rules and decisions for society.', 'I like discussing how to solve problems in my city, school, or community.', 'I enjoy following news about leaders, policies, or social changes.'] },
  { key: 'administration_office_support', label: 'Administration & Office Support', items: ['I like organizing files, schedules, or tasks to keep things running smoothly.', 'I enjoy checking documents for accuracy and details.', 'I feel satisfied when I complete clerical tasks quickly and correctly.'] },
  { key: 'education_teaching', label: 'Education & Teaching', items: ['I enjoy explaining ideas to friends who need help understanding.', 'I like preparing notes, examples, or activities to teach a topic.', 'I feel happy when others learn something because of my help.'] },
  { key: 'physical_science_research', label: 'Physical Science & Research', items: ['I enjoy doing experiments and recording clear observations.', 'I like using maths and logic to explain how things in nature work.', 'I am curious about learning physics, chemistry, or pure mathematics in depth.'] },
  { key: 'social_science_research', label: 'Social Science & Research', items: ['I like observing people and thinking about why they behave a certain way.', 'I enjoy reading about society, history, or economics and their effects.', 'I am curious about conducting simple surveys or interviews to learn more.'] },
  { key: 'engineering_core', label: 'Engineering (Core)', items: ['I enjoy building or fixing things using tools or kits.', 'I like understanding how machines, bridges, or buildings are designed.', 'I am curious about applying maths and science to solve practical problems.'] },
  { key: 'it_software_development', label: 'IT & Software Development', items: ['I enjoy writing simple code or using apps to automate tasks.', 'I like breaking big problems into small steps a computer can follow.', 'I am curious about how software and apps are built.'] },
  { key: 'data_science_analytics', label: 'Data Science & Analytics', items: ['I enjoy finding patterns in numbers, charts, or datasets.', 'I like using evidence to support decisions or predictions.', 'I am curious about how data can answer real-life questions.'] },
  { key: 'artificial_intelligence_robotics', label: 'Artificial Intelligence & Robotics', items: ['I enjoy learning how machines can recognize patterns or make decisions.', 'I like the idea of building or programming robots to do tasks.', 'I am curious about how AI is used in everyday apps and devices.'] },
  { key: 'healthcare_medicine_nursing', label: 'Healthcare (Medicine & Nursing)', items: ['I like the idea of helping people recover from illness or injury.', 'I enjoy learning about how the human body works.', 'I am comfortable with the responsibility needed to care for others’ health.'] },
  { key: 'allied_health_pharmacy_therapy_lab', label: 'Allied Health (Pharmacy, Therapy, Lab)', items: ['I enjoy learning how medicines, tests, or therapies help people improve.', 'I like careful, precise work in labs or treatment settings.', 'I am curious about how pharmacists, therapists, or lab technicians support care.'] },
  { key: 'psychology_counselling', label: 'Psychology & Counselling', items: ['I like listening to friends when they are upset and trying to make them feel better.', 'I am curious about why people think, feel, and behave the way they do.', 'I enjoy giving advice or support when someone asks me for help.'] },
  { key: 'social_work_community_service', label: 'Social Work & Community Service', items: ['I like helping others, especially people who are in need.', 'I enjoy volunteering for school, social, or community projects.', 'I am interested in solving problems that affect society, like poverty or education.'] },
  { key: 'hospitality_tourism', label: 'Hospitality & Tourism', items: ['I enjoy welcoming guests and making them feel comfortable.', 'I like planning trips or experiences that people will enjoy.', 'I am curious about hotels, travel, and tourism services.'] },
  { key: 'event_management', label: 'Event Management', items: ['I enjoy planning events like fests, competitions, or celebrations.', 'I like coordinating people, places, and time so everything works well.', 'I am calm when many tasks must be handled at once.'] },
  { key: 'creative_arts_design', label: 'Creative Arts & Design', items: ['I enjoy drawing, painting, or designing new things.', 'I like experimenting with shapes, colors, or creative ideas.', 'I am curious about how design makes objects, clothes, or spaces look appealing.'] },
  { key: 'performing_arts_music', label: 'Performing Arts & Music', items: ['I enjoy singing, playing music, acting, or dancing in front of people.', 'I like practicing artistic skills to perform better on stage.', 'I feel energized when I can express myself through performance.'] },
  { key: 'journalism_media_communication', label: 'Journalism, Media & Communication', items: ['I enjoy writing or speaking about things that happen around me.', 'I like the idea of interviewing people and sharing their stories.', 'I am curious about how newspapers, TV, or online channels spread news.'] },
  { key: 'writing_content_creation', label: 'Writing & Content Creation', items: ['I enjoy writing stories, blogs, or essays in my free time.', 'I like expressing my thoughts creatively through words or content.', 'I feel excited about creating posts or content that others will read or watch.'] },
  { key: 'architecture_planning', label: 'Architecture & Planning', items: ['I enjoy sketching buildings or spaces and how people will use them.', 'I like thinking about both beauty and function in a structure.', 'I am curious about city planning, maps, and public spaces.'] },
  { key: 'agriculture_environment', label: 'Agriculture & Environment', items: ['I enjoy learning how crops, soil, and weather affect farming.', 'I like protecting nature and thinking of ways to reduce pollution.', 'I am curious about water, plants, animals, and sustainable living.'] },
  { key: 'defence_police_safety_services', label: 'Defence, Police & Safety Services', items: ['I am interested in protecting people and following rules and discipline.', 'I like fitness, training, and team spirit for a larger goal.', 'I am curious about how defence, police, or safety forces work.'] },
  { key: 'operations_management', label: 'Operations Management', items: ['I enjoy improving how work is organized to save time and effort.', 'I like planning resources so tasks happen on schedule.', 'I am curious about how factories or services make things run smoothly.'] },
  { key: 'retail_merchandising', label: 'Retail & Merchandising', items: ['I enjoy arranging products, clothes, or books in an attractive way so people will notice them.', 'I like observing how stores display items and thinking about what makes customers buy them.', 'I am interested in helping people choose the right products when they are shopping.'] },
  { key: 'supply_chain_management', label: 'Supply Chain Management', items: ['I like organizing and planning how things should move from one place to another.', 'I enjoy solving problems when deliveries or resources are delayed.', 'I am curious about how goods travel from factories to shops or homes.'] },
];

export const WORK_ENV_PREFS: { key: string; label: string; items: string[] }[] = [
  { key: 'team_oriented', label: 'Team‑Oriented', items: ['I enjoy working with a group to reach a goal.', 'I like roles where people share ideas and help each other.', 'I feel motivated when I am part of a team.'] },
  { key: 'independent_autonomous', label: 'Independent / Autonomous', items: ['I like finishing tasks on my own without constant supervision.', 'I enjoy planning my own schedule to get work done.', 'I prefer having responsibility for my own results.'] },
  { key: 'structured_organized', label: 'Structured & Organized', items: ['I like clear rules, checklists, and step‑by‑step instructions.', 'I enjoy working in places where the process is well defined.', 'I prefer knowing exactly what to do and when to do it.'] },
  { key: 'fast_paced_dynamic', label: 'Fast‑Paced & Dynamic', items: ['I enjoy environments where things move quickly.', 'I like handling multiple tasks under time pressure.', 'I feel excited when the workday is busy and active.'] },
  { key: 'field_outdoor', label: 'Field / Outdoor', items: ['I enjoy tasks that take me outside or into the field.', 'I like observing and working in real‑world locations.', 'I prefer moving around instead of sitting all day.'] },
  { key: 'client_facing_service', label: 'Client‑Facing & Service', items: ['I enjoy talking to people and solving their problems.', 'I like roles where I meet and help customers or clients.', 'I feel satisfied when someone appreciates my service.'] },
  { key: 'research_analytical', label: 'Research & Analytical', items: ['I enjoy gathering information and understanding patterns.', 'I like reading, analysing, and noting careful observations.', 'I prefer tasks that require deep thinking and accuracy.'] },
  { key: 'creative_studio', label: 'Creative / Studio', items: ['I enjoy spaces that support drawing, designing, or creating.', 'I like trying new ideas and experimenting with designs.', 'I prefer an environment that allows creative freedom.'] },
  { key: 'technology_driven', label: 'Technology‑Driven', items: ['I enjoy using software, devices, or tools to do my work.', 'I like learning new technologies to improve results.', 'I prefer environments where technology is used often.'] },
  { key: 'hands_on_workshop', label: 'Hands‑on / Workshop', items: ['I enjoy assembling, fixing, or building things with tools.', 'I like practical tasks where I can use my hands.', 'I prefer learning by doing rather than only reading.'] },
];

export const JOB_CHAR_PREFS: { key: string; label: string; items: string[] }[] = [
];
