// The digital Ability battery — the founder's real DBDA (David's Battery of
// Differential Abilities, Loratis) subtests, digitised for the /t/ flow.
//
// Seven subtests, at the official DBDA durations and item counts (from the Test
// Administrator instructions): CA 20 · VA 24 (15 synonyms + 9 proverbs) · NA 20 ·
// RA 12 · SA 72 · MA 25 · CL 72. The two speeded subtests (SA, CL) hide their
// timer, exactly like the paper form ("*do not disclose the duration"). Raw
// scores map onto the Loratis norm tables (src/guest/ability-norms.ts).
//
// Verbal items, the reasoning letter-sets and the clerical pairs are the real
// booklet items; their answer keys are derived deterministically (a clerical pair
// is "same" iff the two strings are equal; a closure item's correct option is the
// one true anagram of the target word). Spatial figures are generated by
// construction (a mirror can never equal a rotation, so the key can't disagree
// with the stimulus), and the closure options are generated so exactly one is a
// true anagram — both are correct-by-construction, never a transcription guess.

import type { AbilityKey } from "./ability-norms"

export type SectionKey = AbilityKey

export interface McqItem {
  text: string
  options: string[]
  /** index into options */
  answer: number
  passage?: string
  /** closure (CA): the target word shown degraded above the jumbled options */
  word?: string
}

export interface SpatialTrial { shape: number; rot: 90 | 180 | 270; mirrored: boolean }
export interface ClericalPair { left: string; right: string; same: boolean }

export interface AbilitySection {
  key: SectionKey
  label: string
  minutes: number
  kind: "mcq" | "closure" | "spatial" | "clerical"
  normed: boolean
  /** speeded subtests hide the countdown (paper form: "do not disclose duration") */
  hideTimer?: boolean
  /** one-line "what this measures" for the section intro */
  measures: string
  /** how to answer, taught before the clock starts */
  how: string
  items?: McqItem[]
  spatial?: SpatialTrial[]
  clerical?: ClericalPair[]
}

const m = (text: string, options: string[], answer: number, passage?: string): McqItem =>
  ({ text, options, answer, ...(passage ? { passage } : {}) })

// ── Closure Ability (CA) — 20 items · 5 min ──────────────────────────────────
// DBDA format: a word appears degraded on the left; among five jumbled letter
// strings you pick the ONE that spells the same word (a true anagram of it). The
// correct option is a scramble of the target; the four distractors are scrambles
// with one letter changed, so exactly one option is a real anagram — the key is
// correct by construction, not read off the booklet.
function seededShuffle<T>(arr: T[], seed: number): T[] {
  const a = arr.slice()
  let s = seed >>> 0
  for (let i = a.length - 1; i > 0; i--) {
    s = (s * 1664525 + 1013904223) >>> 0
    const j = s % (i + 1)
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}
function scrambleWord(word: string, seed: number): string {
  let s = seed, out = seededShuffle(word.split(""), s).join("")
  while (out === word) { s += 101; out = seededShuffle(word.split(""), s).join("") }
  return out
}
function nearMiss(word: string, seed: number): string {
  const chars = word.split("")
  const pos = (seed >>> 0) % chars.length
  const code = chars[pos].charCodeAt(0) - 97
  chars[pos] = String.fromCharCode(97 + ((code + 1 + (seed % 5)) % 26))
  if (chars[pos] === word[pos]) chars[pos] = String.fromCharCode(97 + ((code + 3) % 26))
  return seededShuffle(chars, seed + 17).join("")
}
// real DBDA closure targets (lowercase, no capitals — as in the booklet)
const CA_WORDS = [
  "brand", "illness", "window", "again", "organizer", "mirror", "water", "success",
  "leading", "flank", "terminal", "audience", "jolly", "healthy", "pleasant",
  "since", "gambling", "camera", "nation", "cannot",
]
const CLOSURE: McqItem[] = CA_WORDS.map((word, i) => {
  const correct = scrambleWord(word, i * 31 + 7)
  const distractors = [0, 1, 2, 3].map((k) => nearMiss(word, i * 53 + k * 29 + 11))
  const pos = i % 5
  const options = [...distractors.slice(0, pos), correct, ...distractors.slice(pos)]
  return { word, options, answer: pos, text: "" }
})

// ── Verbal Ability (VA) — 24 items · 8 min ───────────────────────────────────
// Part 1 (1–15): choose the word closest in meaning. Part 2 (16–24): choose the
// saying that means the same as the proverb. Real DBDA items; keys derived.
const VERBAL: McqItem[] = [
  m("Closest in meaning — FAST", ["Old", "Rapid", "Slow", "Early", "Late"], 1),
  m("Closest in meaning — DECEIVE", ["Blunder", "Obtain", "Conceal", "Mislead", "Disclose"], 3),
  m("Closest in meaning — EXCESS", ["Waste", "Departure", "Surplus", "Tax", "Approach"], 2),
  m("Closest in meaning — BELIEVABLE", ["Admirable", "Real", "Personable", "Unlikely", "Credible"], 4),
  m("Closest in meaning — CONTEMPLATE", ["Heal", "Advance", "Meditate", "Rest", "Worry"], 2),
  m("Closest in meaning — AMIABLE", ["Friendly", "Humorous", "Healthy", "Convincing", "Polished"], 0),
  m("Closest in meaning — TURMOIL", ["Circular", "Turbulent", "Calm", "Spinning", "Air-borne"], 1),
  m("Closest in meaning — DECEPTIVE", ["Illogical", "Illusory", "Magical", "Visible", "Clear"], 1),
  m("Closest in meaning — WHIMSICAL", ["Unlike", "Musical", "Dancing", "Unpredictable", "Equatorial"], 3),
  m("Closest in meaning — APATHETIC", ["Ignorant", "Indifferent", "Pitiful", "Concerned", "Clever"], 1),
  m("Closest in meaning — ARDUOUS", ["Repulsive", "Loving", "Easy", "Interesting", "Strenuous"], 4),
  m("Closest in meaning — PLACATE", ["Cover", "Beautify", "Arouse", "Plasticize", "Appease"], 4),
  m("Closest in meaning — CLANDESTINE", ["Furtive", "Safe", "Tribal", "Open", "Healthful"], 0),
  m("Closest in meaning — VINDICATE", ["Deny", "State", "Persecute", "Defend", "Accuse"], 3),
  m("Closest in meaning — INCULCATE", ["Grow", "Inquire", "Instill", "Compute", "Acquire"], 2),
  m("Same meaning — “Strike while the iron is hot”", [
    "Take things as you find them", "Hot love is soon cold", "Make hay while the sun shines",
    "First think and then speak", "Look before you leap",
  ], 2),
  m("Same meaning — “It never rains but it pours”", [
    "Cloudy mornings turn to clear evenings", "Misfortunes never come one at a time", "Easy come, easy go",
    "The least predictable thing in life is the weather", "Every cloud has a silver lining",
  ], 1),
  m("Same meaning — “Let sleeping dogs lie”", [
    "As you made your bed, so you must lie on it", "Do not keep a dog and bark yourself",
    "There will be sleeping enough in the grave", "Never look for trouble; let trouble look for you",
    "An old dog does not bark for nothing",
  ], 3),
  m("Same meaning — “There is no venom like that of the tongue”", [
    "The tongue of an idle person is never idle", "Talking pays no toll", "Few words are best",
    "Words cut more than swords", "Bad news travels fast",
  ], 3),
  m("Same meaning — “It is always darkest before the dawn”", [
    "The longest day means the shortest night", "What is done by night appears by day",
    "He who runs in the dark may well stumble", "He who gropes in the dark finds what he would not",
    "When things are at the worst they will improve",
  ], 4),
  m("Same meaning — “All that glitters is not gold”", [
    "Don’t judge a book by its cover", "All men can’t be masters", "Gold dust blinds all eyes",
    "Money is the root of all evil", "Riches alone will not make a man happy",
  ], 0),
  m("Same meaning — “Too many cooks spoil the broth”", [
    "Too much praise is a burden", "Too much consulting confounds", "Truth needs not many words",
    "Actions speak louder than words", "When need is highest, help is nighest",
  ], 1),
  m("Same meaning — “A stitch in time saves nine”", [
    "It is never too late to mend", "Time cures all things", "Prevention is better than cure",
    "Take time while time is, for time will away", "It is no use crying over spilled milk",
  ], 2),
  m("Same meaning — “Little strokes fell great oaks”", [
    "Step after step the ladder is ascended", "Great strokes make not sweet music",
    "Tall oaks from little acorns grow", "Oaks may fall when reeds stand the storm",
    "Little things please little minds",
  ], 0),
]

// ── Numerical Ability (NA) — 20 items · 5 min 30 s ───────────────────────────
// Real DBDA arithmetic; keys computed. (Two booklet items whose scanned operands
// were ambiguous are replaced by clean equivalents in the same style.)
const NUMERICAL: McqItem[] = [
  m("41 + 57 + 88 + 34 = ?", ["230", "218", "200", "220", "219"], 3),
  m("967 − 435 = ?", ["552", "532", "522", "531", "523"], 1),
  m("974 × 3 = ?", ["2822", "2582", "2922", "2893", "2904"], 2),
  m("2226 ÷ 7 = ?", ["318", "316", "324", "326", "213"], 0),
  m("253 × 20 = ?", ["5050", "5060", "4760", "4750", "4050"], 1),
  m("952 − 727 = ?", ["224", "234", "235", "225", "325"], 3),
  m("9 3/5 + 6 1/2 = ?", ["16 1/10", "16 1/5", "15 4/5", "15 1/10", "15 9/10"], 0),
  m("9.6 ÷ 8 = ?", ["1.2", "15.0", "12.0", "0.12", "1.5"], 0),
  m("4.52 × 5 = ?", ["22.60", "22.50", "22.40", "22.26", "26.10"], 0),
  m("1050 ÷ 15 = ?", ["30", "32", "70", "72", "60"], 2),
  m("2 × (25 − 19) ÷ 9 = ?", ["2/3", "1 1/3", "1 1/9", "1 7/9", "2 2/5"], 1),
  m("Which number replaces X in both places:  4 + X = 6 − X ?", ["4", "3", "2", "1", "−2"], 3),
  m("7/8 × (7/10 − 3/5) = ?", ["39/40", "7/40", "1 11/80", "2 11/40", "7/80"], 4),
  m("35 3/4 − 28 2/3 = ?", ["7 1/6", "7 5/6", "7 1/12", "6 11/12", "6 5/6"], 2),
  m("125% of 32 = ?", ["6", "12", "36", "52", "40"], 4),
  m("√196 = ?", ["14", "16", "24", "36", "98"], 0),
  m("5/7 of 245 = ?", ["165", "175", "185", "207", "343"], 1),
  m("(1/2 − 1/3) ÷ 3/4 = ?", ["1/3", "1/8", "2/9", "1 1/9", "5/8"], 2),
  m("1/2 + 1/3 + 1/6 = ?", ["1", "5/6", "2/3", "11/12", "7/6"], 0),
  m("(2/3 × 5/6) + 1/3 = ?", ["1 5/6", "5/27", "1 1/9", "8/9", "7/9"], 3),
]

// ── Reasoning Ability (RA) — 12 items · 5 min ────────────────────────────────
// Real DBDA letter-set items: four of the five sets follow one rule, one breaks
// it — pick the odd one out. Keys derived by solving each rule.
const R = (sets: [string, string, string, string, string], answer: number): McqItem =>
  ({ text: "Four of these five sets follow one rule. Mark the ONE that does not.", options: sets, answer })
const REASONING: McqItem[] = [
  R(["DEPD", "RFMR", "SJUS", "TVWT", "GBBK"], 4), // first letter = last letter; GBBK breaks
  R(["XFGX", "BLMB", "KQRK", "DTSD", "MYZM"], 3), // middle two ascend; DTSD (T,S) descends
  R(["FGHE", "IJKH", "LMNP", "RSTQ", "VWXU"], 2), // last = first − 1; LMNP breaks
  R(["EDDG", "IHHJ", "NMMO", "RQQS", "TSSU"], 0), // last = first + 1; EDDG (+2) breaks
  R(["VWVT", "SVWV", "VWVR", "QVWV", "VWPV"], 4), // contains VWV; VWPV breaks
  R(["CDED", "LMOM", "PQRQ", "STUT", "WXYX"], 1), // X,X+1,X+2,X+1; LMOM skips a letter
  R(["RYAA", "BBRG", "RPCC", "DDRD", "RLEE"], 3), // one doubled series letter + R; DDRD has three D
  R(["ORAR", "PGRR", "RBVR", "RRUH", "LRLX"], 4), // two R's; LRLX has one
  R(["DECG", "JKIL", "MNLO", "QRPS", "UVTW"], 0), // X,X+1,X−1,X+2; DECG last is +3
  R(["BCFF", "GHKK", "KLNN", "PQTT", "VWZZ"], 2), // doubled = 2nd + 3; KLNN is +2
  R(["CGFJ", "EIHL", "GKJN", "IMNR", "MQPT"], 3), // X,X+4,X+3,X+7; IMNR breaks
  R(["HGFC", "KJIG", "NMLI", "TSRO", "YXWT"], 1), // last = 3rd − 3; KJIG is −2
]

// ── Mechanical Ability (MA) — 25 items · 9 min ───────────────────────────────
// The DBDA MA booklet is figure-based (gears, pulleys, levers). These 25 items
// reproduce the same physical-reasoning content in text form, with correct keys.
const MECHANICAL: McqItem[] = [
  m("If gear A rotates clockwise, gear B meshed directly with it rotates:", ["clockwise", "anticlockwise", "not at all", "up and down"], 1),
  m("A seesaw is an example of which class of lever?", ["First class", "Second class", "Third class", "Not a lever"], 0),
  m("Which pulley arrangement needs the least effort to lift a load?", ["Single fixed pulley", "Single movable pulley", "Block and tackle (several pulleys)", "No pulley"], 2),
  m("A 4-cylinder four-stroke engine produces how many power strokes per 2 revolutions?", ["1", "2", "4", "8"], 2),
  m("Which device converts electrical energy into mechanical energy?", ["Generator", "Motor", "Battery", "Transformer"], 1),
  m("A knife is an example of which simple machine?", ["Lever", "Wedge", "Pulley", "Screw"], 1),
  m("If you push an object to the right, it moves:", ["left", "right", "upwards", "it cannot move"], 1),
  m("What transfers motion from the pedals to the wheel of a bicycle?", ["Belt", "Chain", "Rope", "Spring"], 1),
  m("Which of these materials conducts electricity?", ["Wood", "Rubber", "Copper", "Plastic"], 2),
  m("Which arrangement increases torque (turning force)?", ["Small gear driving a big gear", "Big gear driving a small gear", "Equal gears", "Torque cannot change"], 0),
  m("A wheelbarrow is an example of which class of lever?", ["First class", "Second class", "Third class", "Not a lever"], 1),
  m("An inclined plane (ramp) reduces the:", ["distance moved", "force needed", "weight of the load", "friction to zero"], 1),
  m("A screw is best described as:", ["a wedge joined to a lever", "an inclined plane wrapped around a cylinder", "a wheel and axle", "a pulley"], 1),
  m("Friction between moving parts is reduced by:", ["adding sand", "lubrication with oil", "pressing harder", "using rougher surfaces"], 1),
  m("Pressure equals:", ["force × area", "force ÷ area", "area ÷ force", "force + area"], 1),
  m("Hydraulic brakes work on the principle of:", ["Newton's first law", "Pascal's law", "Ohm's law", "Hooke's law"], 1),
  m("A single fixed pulley changes the:", ["amount of force needed", "direction of the force", "weight of the load", "speed of the load"], 1),
  m("An object denser than water will:", ["float", "sink", "dissolve", "evaporate"], 1),
  m("Heat naturally flows from:", ["cold to hot", "hot to cold", "left to right", "it never flows"], 1),
  m("A longer spanner makes a tight nut easier to open because it:", ["weighs more", "increases the turning effect", "reduces the nut's size", "heats the nut"], 1),
  m("Two gears connected by a chain (like a bicycle) rotate:", ["in the same direction", "in opposite directions", "at right angles", "not at all"], 0),
  m("A 20-tooth gear drives a 40-tooth gear. The 40-tooth gear turns:", ["twice as fast", "half as fast", "at the same speed", "four times as fast"], 1),
  m("Sound travels fastest through:", ["vacuum", "air", "water", "steel"], 3),
  m("A transformer works only with:", ["direct current", "alternating current", "static charge", "magnets alone"], 1),
  m("Lowering an object's centre of gravity makes it:", ["less stable", "more stable", "heavier", "faster"], 1),
]

// ── Spatial Ability (SA) — 72 trials · 6 min (speeded, timer hidden) ─────────
// Each trial shows a TARGET figure and a PROBE. The probe is the same figure
// merely ROTATED (answer R) or its MIRROR image (answer S). All 12 base shapes
// are asymmetric, so a mirror can never equal a rotation — the key is correct by
// construction. Twelve distinct shapes cycle so no two adjacent trials repeat.
export const SPATIAL_SHAPES: string[] = [
  "20,90 20,10 70,10 70,30 40,30 40,45 60,45 60,65 40,65 40,90", // F
  "25,10 45,10 45,70 80,70 80,90 25,90", // L
  "25,90 25,10 65,10 75,20 75,45 65,55 45,55 45,90", // P
  "30,90 30,10 80,25 30,40", // flag
  "20,20 55,20 55,45 85,45 85,85 65,85 65,60 20,60", // zigzag step
  "20,80 50,20 60,25 45,55 80,55 80,70 35,70", // angled hook
  "25,15 45,15 45,55 65,55 65,35 85,35 85,90 65,90 65,75 25,75", // key
  "15,85 15,65 35,65 35,45 55,45 55,25 85,25 85,40 70,40 70,60 50,60 50,80 35,80 35,85", // staircase
  "70,15 30,15 20,35 30,70 70,80 70,60 45,55 40,40 70,35", // G-hook
  "20,15 20,90 40,90 40,55 65,55 65,90 85,90 85,15 65,15 65,38 40,38 40,15", // H/goalpost
  "15,20 85,20 85,40 55,40 55,90 35,90 35,40 15,40", // T
  "25,20 75,20 75,45 45,45 45,60 70,60 70,80 25,80", // S/Z-bend
]
const MIRROR_PATTERN = [
  false, true, false, false, true, true, false, true, // 1-8
  true, false, true, false, false, true, false, true, // 9-16
  false, false, true, true, false, true, true, false, // 17-24
  true, true, false, true, false, false, true, false, // 25-32
  false, true, true, false, true, false, false, true, // 33-40
  true, false, false, true, true, false, true, false, // 41-48
  false, true, false, true, false, true, true, false, // 49-56
  true, false, true, false, true, false, false, true, // 57-64
  false, true, true, false, true, false, true, false, // 65-72
]
const ROTS: (90 | 180 | 270)[] = [90, 180, 270]
export const SPATIAL_TRIALS: SpatialTrial[] = MIRROR_PATTERN.map((mirrored, i) => ({
  // 12 distinct shapes in a row (no adjacent repeat) AND the rotation advances each
  // pass, so a shape that recurs 12 later is at a different angle — no visible recycle
  shape: i % SPATIAL_SHAPES.length,
  rot: ROTS[Math.floor(i / SPATIAL_SHAPES.length) % 3],
  mirrored,
}))

// ── Clerical Ability (CL) — 72 pairs · 3 min (speeded, timer hidden) ─────────
// The 72 REAL DBDA comparison pairs. Mark Same if the two entries are identical,
// Different if anything differs. `same` is derived by string equality, so the key
// can never disagree with what is shown.
const CLERICAL_RAW: [string, string][] = [
  ["1013295", "1012395"], ["krqpdisu", "krqpdisu"], ["79318453", "79318435"], ["KLSQAEPD", "KLSQAEPD"],
  ["pdesqidt", "pdesqidt"], ["JQRASMNP", "JQRASNMP"], ["RMAPIQUV", "RMAPIQUV"], ["jnlvupdi", "jnluvpdi"],
  ["59412675", "59412765"], ["jlnvoprdi", "jlvnoprdi"], ["3645179", "3645179"], ["KRINQUSR", "KRINQUSR"],
  ["VFGARTUX", "VFGARUTX"], ["732837914", "732387914"], ["JVOPIMURA", "JVOPIMURA"], ["bxvinygru", "bxvinygur"],
  ["784513962", "784513926"], ["ARQULEWVP", "ARQULEVWP"], ["mnovprydc", "mnovprdyc"], ["793148252", "793148252"],
  ["XYBWUTYR", "XYBWUTYR"], ["zrmpfdgh", "zrmpfgdh"], ["825731496", "825731496"], ["HUMPRJEQ", "HUMPREJQ"],
  ["derpqmljn", "derpqmljn"], ["592614826", "592614286"], ["PDLMARQUJ", "PDLMARQUJ"], ["iqrspdelm", "iqsrpdelm"],
  ["JMNVUPAL", "JMNUVPAL"], ["913826574", "913826574"], ["cpdekrsqb", "cpdekrsqb"], ["AXPRWNBG", "AXPRWNBG"],
  ["294733506", "294733506"], ["CDJLQRSKN", "CDJLQSRKN"], ["reqlmjxap", "reqlmxjap"], ["ZYBMOPRQS", "ZYBMOPRQS"],
  ["3814569", "3814659"], ["qmlavwn", "qmlavwn"], ["ERYNODFP", "ERYNODFP"], ["187935824", "187953824"],
  ["NMRAPCUH", "NMRAPCUH"], ["fvbosdrn", "fvbosrdn"], ["631425719", "631425719"], ["TRCHLMOV", "TRCHMLOV"],
  ["cgierduj", "cgierduj"], ["DNWLRVAX", "DNWLRAXV"], ["hijuvmlpr", "hijuvmlpr"], ["GVAPORJM", "GVAPORJM"],
  ["81423596", "81243596"], ["KIRJSBMO", "KIRJSBMO"], ["oqxjarpd", "oqxjaprd"], ["64937215", "64937215"],
  ["XBAJZPOR", "XBAJZPOR"], ["qzbrsaqt", "qzbrsaqt"], ["63495712", "63459712"], ["PMAZRSTQE", "PMAZRSTQE"],
  ["bcxpudef", "bcxpudef"], ["51936247", "51936247"], ["JXRASPUV", "JXRASPVU"], ["drpewye", "drepwye"],
  ["4562908", "4569208"], ["MDACPURN", "MDACPURN"], ["lmnrdopsa", "lmnrdapso"], ["271659325", "271695325"],
  ["IPRSABJM", "IPRSABJM"], ["brpdavul", "brpdauvl"], ["91352748", "91352748"], ["KRIMNFOJ", "KRINMFOJ"],
  ["61825739", "61825739"], ["MPORSJNV", "MPORSJNV"], ["rbapdnuz", "rbapdnuz"], ["LKUVMPOZ", "LKVUMPOZ"],
]
export const CLERICAL_PAIRS: ClericalPair[] = CLERICAL_RAW.map(([left, right]) => ({ left, right, same: left === right }))

// ── Battery ──────────────────────────────────────────────────────────────────
export const ABILITY_SECTIONS: AbilitySection[] = [
  {
    key: "CA", label: "Closure Ability", minutes: 5, kind: "closure", normed: true,
    measures: "Completing partial information — recognising a whole word from a degraded image of it.",
    how: "A word appears with parts of its letters missing. Work out the word, then choose the ONE jumbled option that uses exactly the same letters. Keys 1–5 select.",
    items: CLOSURE,
  },
  {
    key: "VA", label: "Verbal Ability", minutes: 8, kind: "mcq", normed: true,
    measures: "Vocabulary and verbal meaning — the closest synonym, then the matching proverb.",
    how: "First fifteen: choose the word closest in meaning. Last nine: choose the saying that means the same as the proverb. Keys 1–5 select, Enter confirms.",
    items: VERBAL,
  },
  {
    key: "NA", label: "Numerical Ability", minutes: 6, kind: "mcq", normed: true,
    measures: "Arithmetic and everyday quantitative problem-solving — no calculator.",
    how: "Work each problem on the rough sheet, then choose the answer. No calculators.",
    items: NUMERICAL,
  },
  {
    key: "RA", label: "Reasoning Ability", minutes: 5, kind: "mcq", normed: true,
    measures: "Abstract rule-finding — spotting the set of letters that breaks the pattern.",
    how: "Four of the five letter-sets follow one hidden rule; one does not. Choose the odd one out. Keys 1–5 select.",
    items: REASONING,
  },
  {
    key: "SA", label: "Spatial Ability", minutes: 6, kind: "spatial", normed: true, hideTimer: true,
    measures: "Mental rotation — recognising a shape when it is turned, versus its mirror image.",
    how: "Two figures appear. If the right-hand figure is the SAME shape merely rotated, answer Rotated (R). If it is a mirror image, answer Mirrored (S). Work as fast as you accurately can.",
  },
  {
    key: "MA", label: "Mechanical Ability", minutes: 9, kind: "mcq", normed: true,
    measures: "Physical cause and effect — gears, levers, forces and simple machines.",
    how: "Picture the mechanism, then choose what happens. Keys 1–4 select.",
    items: MECHANICAL,
  },
  {
    key: "CL", label: "Clerical Ability", minutes: 3, kind: "clerical", normed: true, hideTimer: true,
    measures: "Speed and accuracy with detail — checking whether two entries match.",
    how: "Two entries appear side by side. Press S if they are exactly the SAME, D if anything differs. Work fast — small slips count.",
  },
]

export const ABILITY_TOTAL_MINUTES = ABILITY_SECTIONS.reduce((a, s) => a + s.minutes, 0)

export function sectionItemCount(s: AbilitySection): number {
  return s.kind === "spatial" ? SPATIAL_TRIALS.length
    : s.kind === "clerical" ? CLERICAL_PAIRS.length
    : s.items!.length
}

/** Score one section from its answer array (null = unanswered). MCQ/closure
 *  answers are option indices; spatial answers are "R"/"S"; clerical "S"/"D". */
export function rawScore(section: AbilitySection, answers: (number | string | null)[]): { raw: number; attempted: number } {
  let raw = 0, attempted = 0
  const n = sectionItemCount(section)
  for (let i = 0; i < n; i++) {
    const a = answers[i]
    if (a == null) continue
    attempted++
    if (section.kind === "spatial") { if ((a === "S") === SPATIAL_TRIALS[i].mirrored) raw++ }
    else if (section.kind === "clerical") { if ((a === "S") === CLERICAL_PAIRS[i].same) raw++ }
    else { if (a === section.items![i].answer) raw++ }
  }
  return { raw, attempted }
}
